### ISSUE TITLE
PDAC data

### ISSUE THREAD

**Issue by jiazhao97** [MarcElosua/SPOTlight_deconvolution_analysis#3]
Hi @MarcElosua,

Thank you for you nice work SPOTlight! 

From GSE111672, I can not find annotations for scRNA-seq data, and detailed data (e.g., filtered_feature_bc_matrix.tsv, tissue_positions_list_spatial_object.tsv, lowres_rot.jpg) for ST. 

For example, when I tried to download PDAC-A ST1, I opened [this link](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3036911), but I could not find files including filtered_feature_bc_matrix.tsv, tissue_positions_list_spatial_object.tsv, and lowres_rot.jpg.

Would you provide a more detailed description on downloading PDAC data? Thanks.

Best,
Jia

**Comment by leihouyeung** [comment]
Same situation. I cannot find the annotation of scRNA-seq data in GSE111672 either.

**Comment by jiazhao97** [comment]
It would be very helpful if tutorials on visualizing data and inputing it to SPOTlight are provided. I find it hard to visualize PDAC-A ST1 histology together with spots, which has been done in the publication for SPOTlight. Thanks in advance!

**Comment by MarcElosua** [comment]
Hi @leihouyeung!
Please note that the data stored in GSE111672 had already been published, since it was publicly available we were able to use it as well to benchmark SPOTlight. If you can share your email with me I am more than happy sharing the processed data with you.

**Comment by MarcElosua** [comment]
Hi @jiazhao97 ,
I don't fully understand what you mean by finding it hard to visualize PDAC-A ST1 together with the spots.

**Comment by adamdingliang** [comment]
Hi @MarcElosua,

Have been watching SPOTLIGHT for a while. Very useful tool!

I have the same problem with @jiazhao97 . Can you please share the processed ST data (filtered_feature_bc_matrix.tsv, tissue_positions_list_spatial_object.tsv, lowres_rot.jpg) with me? My email address is lding@stjude.org.

Thanks!
Liang (Adam) Ding

**Comment by leihouyeung** [comment]
> Hi @leihouyeung!
> Please note that the data stored in GSE111672 had already been published, since it was publicly available we were able to use it as well to benchmark SPOTlight. If you can share your email with me I am more than happy sharing the processed data with you.

Thanks so much for your response. My email address is haoyang.li@kaust.edu.sa

**Comment by jiazhao97** [comment]
Hi @MarcElosua,

Thanks so much for sharing the zip file. However, unfortunately I can not load it.
![image](https://user-images.githubusercontent.com/45305585/112423129-0b91fa80-8d6d-11eb-9080-98c7cceb236d.png)

I know that this dataset is already published, what puzzled me is that I can not find the pixel locations of spots (at the same scale of HE figure). Although there are spot locations like 10x10, 11x12, 25x26... However, I do not know how this 'integer x integer' location can be mapped on HE figure, because spot locations and HE figure pixels have different scales.

Looking forward to your reply. Thanks.
Jia

**Comment by MarcElosua** [comment]
hi @jiazhao97 ,
Can you please try to open the file using `readRDS()` instead of `load()`. As this is an RDS file and not an Rdata reading it with the specific function should do the trick!
```

sc_a <- readRDS("~/Downloads/Itai_PDAC/Itai_files/PDAC-A_itai_joint.RDS")

sp_a <- readRDS("~/Downloads/Itai_PDAC/Itai_files/PDAC-A_ST_list.RDS")

sc_b <- readRDS("~/Downloads/Itai_PDAC/Itai_files/PDAC-B_itai_joint.RDS")

sp_b <- readRDS("~/Downloads/Itai_PDAC/Itai_files/PDAC-B_ST_list.RDS")
```

**Comment by leihouyeung** [comment]
Hello @MarcElosua ,

Thanks for sharing these files. I cannot find the coordinates of each spot in the image. I just saw the relative spatial positions of all spots, but I would like to map these spots to the tissue images. Thus, I need the spot's coordinates in the tissue image. Could you please help me with this? Thanks a lot!

**Comment by johannesnicolaus** [comment]
Hi @MarcElosua, I sent an email a while back but I'm afraid it might have gone to your spam folder.

I'm having the same problem with others in this issue thread. Is it possible for you to share the files with me too? My email is nico@protein.osaka-u.ac.jp

Best,
Nico

**Comment by mqHao** [comment]
Hi @MarcElosua,

Thank you very much for your wonderful work SPOTlight!

I have the same problem with others. It would be very helpful if the processed ST data (filtered_feature_bc_matrix.tsv, tissue_positions_list_spatial_object.tsv, lowres_rot.jpg) can be shared. My email address is mengqianhao@whu.edu.cn.

Thanks!
Mengqian Hao

**Comment by Han117** [comment]
Hi @MarcElosua, I sent an email a while back but I'm afraid it might have gone to your spam folder.

I'm having the same problem with others in this issue thread. Is it possible for you to share the files with me too? My email is wdhan596@gmail.com

Best,
