### ISSUE TITLE
tool_benchmarking

### ISSUE THREAD

**Issue by EmmaSwan13** [MarcElosua/SPOTlight_deconvolution_analysis#4]
Hi Marc,

Your SPOTlight package is pretty awesome. I have a little question about the code. In common_synthetic_spots.Rmd, there is a line of code, "source(here::here("misc/paths_vrs.R"))". But I couldn't find the folder "misc". Could you give me some help and explain the code? 

Thank you a lot!

BW

Yu

**Comment by MarcElosua** [comment]
Hi @EmmaSwan13 ,
Thanks a lot for your interest!
I just uploaded the file `misc/paths_vrs.R`, briefly this script serves as the mastermind connecting the scripts between them when there are files that one produces and others require.

**Comment by EmmaSwan13** [comment]
Thank you for your help! It is really helpful for me.

**Comment by pengfeigaonice** [comment]
Hi Marc,

I have a little question about the code. In common_synthetic_spots.Rmd, there is a line of code, "load(here::here("data/techs/sce.all_classified.technologies.RData"))". But I couldn't find the folder "data/techs/sce.all_classified.technologies.RData". Could you give me some help and explain the code?

Thank you very much!
best wishes!
