### ISSUE TITLE
spotlight_deconvolution function

### ISSUE THREAD

**Issue by ccomo0730** [MarcElosua/SPOTlight_deconvolution_analysis#5]
Hello, I am currently running the SPOTlight package and attempting the spotlight decomposition portion of the. code on my reference scRNAseq data. The code I am running is below:
#Spotlight decomposition 
set.seed(123)
spotlight_ls <-spotlight_deconvolution(
  se_sc = E14_sc,
  counts_spatial = anterior@assays$RNA@counts,
  clust_vr = "subclass", # Variable in sc_seu containing the cell-type annotation
  cluster_markers = cluster_markers_all, # Dataframe with the marker genes
  cl_n = 100, # number of cells per cell type to use
  hvg = 3000, # Number of HVG to use
  ntop = NULL, # How many of the marker genes to use (by default all)
  transf = "uv", # Perform unit-variance scaling per cell and spot prior to factorzation and NLS
  method = "nsNMF", # Factorization method
  min_cont = 0 # Remove those cells contributing to a spot below a certain threshold 
)

When I run this code, I get the following error: Error in spotlight_deconvolution(se_sc = E14_sc, counts_spatial = anterior@assays$RNA@counts,  : 
  could not find function "spotlight_deconvolution"

Here are all of the libraries I have loaded:
library(NMF)
library(SPOTlight)
library(Matrix)
library(data.table)
library(Seurat)
library(SeuratData)
library(dplyr)
library(gt)
library(igraph)
library(RColorBrewer)
library(ggplot2)
library(purrr)
library(nnls)
library(scrattch.io)
library(Spaniel)
library(igraph)
library(SeuratDisk)
library(future)

Here is my SessionInfo:
version  R version 4.1.2 (2021-11-01)
 os       macOS Monterey 12.0.1
 system   x86_64, darwin17.0
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       America/Denver
 date     2022-01-23
 rstudio  2021.09.0+351 Ghost Orchid (desktop)
 pandoc   2.14.0.3 @ /Applications/RStudio.app/Contents/MacOS/pandoc/ (via rmarkdown)

─ Packages ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package              * version    date (UTC) lib source
 abind                  1.4-5      2016-07-21 [1] CRAN (R 4.1.0)
 assertthat             0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
 backports              1.4.1      2021-12-13 [1] CRAN (R 4.1.0)
 beachmat               2.10.0     2021-10-26 [1] Bioconductor
 Biobase              * 2.54.0     2021-10-26 [1] Bioconductor
 BiocGenerics         * 0.40.0     2021-10-26 [1] Bioconductor
 BiocManager            1.30.16    2021-06-15 [1] CRAN (R 4.1.0)
 BiocNeighbors          1.12.0     2021-10-26 [1] Bioconductor
 BiocParallel           1.28.3     2021-12-09 [1] Bioconductor
 BiocSingular           1.10.0     2021-10-26 [1] Bioconductor
 bit                    4.0.4      2020-08-04 [1] CRAN (R 4.1.0)
 bit64                  4.0.5      2020-08-30 [1] CRAN (R 4.1.0)
 bitops                 1.0-7      2021-04-24 [1] CRAN (R 4.1.0)
 bluster                1.4.0      2021-10-26 [1] Bioconductor
 brio                   1.1.3      2021-11-30 [1] CRAN (R 4.1.0)
 cachem                 1.0.6      2021-08-19 [1] CRAN (R 4.1.0)
 callr                  3.7.0      2021-04-20 [1] CRAN (R 4.1.0)
 checkmate              2.0.0      2020-02-06 [1] CRAN (R 4.1.0)
 cli                    3.1.1      2022-01-20 [1] CRAN (R 4.1.2)
 cluster              * 2.1.2      2021-04-17 [1] CRAN (R 4.1.2)
 codetools              0.2-18     2020-11-04 [1] CRAN (R 4.1.2)
 colorRamps             2.3        2012-10-29 [1] CRAN (R 4.1.0)
 colorspace             2.0-2      2021-06-24 [1] CRAN (R 4.1.0)
 cowplot                1.1.1      2020-12-30 [1] CRAN (R 4.1.0)
 crayon                 1.4.2      2021-10-29 [1] CRAN (R 4.1.0)
 curl                   4.3.2      2021-06-23 [1] CRAN (R 4.1.0)
 data.table           * 1.14.2     2021-09-27 [1] CRAN (R 4.1.0)
 DBI                    1.1.2      2021-12-20 [1] CRAN (R 4.1.2)
 DelayedArray           0.20.0     2021-10-26 [1] Bioconductor
 DelayedMatrixStats     1.16.0     2021-10-26 [1] Bioconductor
 deldir                 1.0-6      2021-10-23 [1] CRAN (R 4.1.0)
 desc                   1.4.0      2021-09-28 [1] CRAN (R 4.1.0)
 devtools             * 2.4.3      2021-11-30 [1] CRAN (R 4.1.0)
 digest                 0.6.29     2021-12-01 [1] CRAN (R 4.1.0)
 doParallel             1.0.16     2020-10-16 [1] CRAN (R 4.1.0)
 dplyr                * 1.0.7      2021-06-18 [1] CRAN (R 4.1.0)
 dqrng                  0.3.0      2021-05-01 [1] CRAN (R 4.1.0)
 edgeR                  3.36.0     2021-10-26 [1] Bioconductor
 ellipsis               0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
 evaluate               0.14       2019-05-28 [1] CRAN (R 4.1.0)
 fansi                  1.0.2      2022-01-14 [1] CRAN (R 4.1.2)
 farver                 2.1.0      2021-02-28 [1] CRAN (R 4.1.0)
 fastmap                1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
 fitdistrplus           1.1-6      2021-09-28 [1] CRAN (R 4.1.0)
 foreach                1.5.1      2020-10-15 [1] CRAN (R 4.1.0)
 fs                     1.5.2      2021-12-08 [1] CRAN (R 4.1.0)
 future               * 1.23.0     2021-10-31 [1] CRAN (R 4.1.0)
 future.apply           1.8.1      2021-08-10 [1] CRAN (R 4.1.0)
 generics               0.1.1      2021-10-25 [1] CRAN (R 4.1.0)
 GenomeInfoDb           1.30.0     2021-10-26 [1] Bioconductor
 GenomeInfoDbData       1.2.7      2021-12-17 [1] Bioconductor
 GenomicRanges          1.46.1     2021-11-18 [1] Bioconductor
 ggplot2              * 3.3.5      2021-06-25 [1] CRAN (R 4.1.0)
 ggrepel                0.9.1      2021-01-15 [1] CRAN (R 4.1.0)
 ggridges               0.5.3      2021-01-08 [1] CRAN (R 4.1.0)
 globals                0.14.0     2020-11-22 [1] CRAN (R 4.1.0)
 glue                   1.6.1      2022-01-22 [1] CRAN (R 4.1.2)
 goftest                1.2-3      2021-10-07 [1] CRAN (R 4.1.0)
 gridBase               0.4-7      2014-02-24 [1] CRAN (R 4.1.0)
 gridExtra              2.3        2017-09-09 [1] CRAN (R 4.1.0)
 gt                   * 0.3.1      2021-08-07 [1] CRAN (R 4.1.0)
 gtable                 0.3.0      2019-03-25 [1] CRAN (R 4.1.0)
 hdf5r                  1.3.5      2021-11-15 [1] CRAN (R 4.1.0)
 here                   1.0.1      2020-12-13 [1] CRAN (R 4.1.0)
 hms                    1.1.1      2021-09-26 [1] CRAN (R 4.1.0)
 htmltools              0.5.2      2021-08-25 [1] CRAN (R 4.1.0)
 htmlwidgets            1.5.4      2021-09-08 [1] CRAN (R 4.1.0)
 httpuv                 1.6.5      2022-01-05 [1] CRAN (R 4.1.2)
 httr                   1.4.2      2020-07-20 [1] CRAN (R 4.1.0)
 ica                    1.0-2      2018-05-24 [1] CRAN (R 4.1.0)
 igraph               * 1.2.11     2022-01-04 [1] CRAN (R 4.1.2)
 IRanges                2.28.0     2021-10-26 [1] Bioconductor
 irlba                  2.3.5      2021-12-06 [1] CRAN (R 4.1.0)
 iterators              1.0.13     2020-10-15 [1] CRAN (R 4.1.0)
 jsonlite               1.7.3      2022-01-17 [1] CRAN (R 4.1.2)
 KernSmooth             2.23-20    2021-05-03 [1] CRAN (R 4.1.2)
 knitr                  1.37       2021-12-16 [1] CRAN (R 4.1.0)
 labeling               0.4.2      2020-10-20 [1] CRAN (R 4.1.0)
 later                  1.3.0      2021-08-18 [1] CRAN (R 4.1.0)
 lattice                0.20-45    2021-09-22 [1] CRAN (R 4.1.2)
 lazyeval               0.2.2      2019-03-15 [1] CRAN (R 4.1.0)
 leiden                 0.3.9      2021-07-27 [1] CRAN (R 4.1.0)
 lifecycle              1.0.1      2021-09-24 [1] CRAN (R 4.1.0)
 limma                  3.50.0     2021-10-26 [1] Bioconductor
 listenv                0.8.0      2019-12-05 [1] CRAN (R 4.1.0)
 lmtest                 0.9-39     2021-11-07 [1] CRAN (R 4.1.0)
 locfit                 1.5-9.4    2020-03-25 [1] CRAN (R 4.1.0)
 magrittr               2.0.1      2020-11-17 [1] CRAN (R 4.1.0)
 MASS                   7.3-55     2022-01-13 [1] CRAN (R 4.1.2)
 Matrix               * 1.4-0      2021-12-08 [1] CRAN (R 4.1.0)
 MatrixGenerics         1.6.0      2021-10-26 [1] Bioconductor
 matrixStats            0.61.0     2021-09-17 [1] CRAN (R 4.1.0)
 memoise                2.0.1      2021-11-26 [1] CRAN (R 4.1.0)
 metapod                1.2.0      2021-10-26 [1] Bioconductor
 mgcv                   1.8-38     2021-10-06 [1] CRAN (R 4.1.2)
 mime                   0.12       2021-09-28 [1] CRAN (R 4.1.0)
 miniUI                 0.1.1.1    2018-05-18 [1] CRAN (R 4.1.0)
 modeltools             0.2-23     2020-03-05 [1] CRAN (R 4.1.0)
 munsell                0.5.0      2018-06-12 [1] CRAN (R 4.1.0)
 nlme                   3.1-155    2022-01-13 [1] CRAN (R 4.1.2)
 NLP                    0.2-1      2020-10-14 [1] CRAN (R 4.1.0)
 NMF                  * 0.23.0     2020-08-01 [1] CRAN (R 4.1.0)
 nnls                 * 1.4        2012-03-19 [1] CRAN (R 4.1.0)
 parallelly             1.30.0     2021-12-17 [1] CRAN (R 4.1.0)
 patchwork              1.1.1      2020-12-17 [1] CRAN (R 4.1.0)
 pbapply                1.5-0      2021-09-16 [1] CRAN (R 4.1.0)
 pillar                 1.6.4      2021-10-18 [1] CRAN (R 4.1.0)
 pkgbuild               1.3.1      2021-12-20 [1] CRAN (R 4.1.2)
 pkgconfig              2.0.3      2019-09-22 [1] CRAN (R 4.1.0)
 pkgload                1.2.4      2021-11-30 [1] CRAN (R 4.1.0)
 pkgmaker             * 0.32.2     2020-10-20 [1] CRAN (R 4.1.0)
 plotly                 4.10.0     2021-10-09 [1] CRAN (R 4.1.0)
 plyr                   1.8.6      2020-03-03 [1] CRAN (R 4.1.0)
 png                    0.1-7      2013-12-03 [1] CRAN (R 4.1.0)
 polyclip               1.10-0     2019-03-14 [1] CRAN (R 4.1.0)
 prettyunits            1.1.1      2020-01-24 [1] CRAN (R 4.1.0)
 processx               3.5.2      2021-04-30 [1] CRAN (R 4.1.0)
 promises               1.2.0.1    2021-02-11 [1] CRAN (R 4.1.0)
 ps                     1.6.0      2021-02-28 [1] CRAN (R 4.1.0)
 purrr                * 0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
 R6                     2.5.1      2021-08-19 [1] CRAN (R 4.1.0)
 RANN                   2.6.1      2019-01-08 [1] CRAN (R 4.1.0)
 rappdirs               0.3.3      2021-01-31 [1] CRAN (R 4.1.0)
 RColorBrewer         * 1.1-2      2014-12-07 [1] CRAN (R 4.1.0)
 Rcpp                   1.0.8      2022-01-13 [1] CRAN (R 4.1.2)
 RcppAnnoy              0.0.19     2021-07-30 [1] CRAN (R 4.1.0)
 RCurl                  1.98-1.5   2021-09-17 [1] CRAN (R 4.1.0)
 readr                  2.1.1      2021-11-30 [1] CRAN (R 4.1.0)
 registry             * 0.5-1      2019-03-05 [1] CRAN (R 4.1.0)
 remotes                2.4.2      2021-11-30 [1] CRAN (R 4.1.0)
 reshape2               1.4.4      2020-04-09 [1] CRAN (R 4.1.0)
 reticulate             1.23       2022-01-14 [1] CRAN (R 4.1.2)
 rhdf5                * 2.38.0     2021-10-26 [1] Bioconductor
 rhdf5filters           1.6.0      2021-10-26 [1] Bioconductor
 Rhdf5lib               1.16.0     2021-10-26 [1] Bioconductor
 rlang                  0.4.12     2021-10-18 [1] CRAN (R 4.1.0)
 rmarkdown              2.11       2021-09-14 [1] CRAN (R 4.1.2)
 rngtools             * 1.5.2      2021-09-20 [1] CRAN (R 4.1.0)
 ROCR                   1.0-11     2020-05-02 [1] CRAN (R 4.1.0)
 rpart                  4.1-15     2019-04-12 [1] CRAN (R 4.1.2)
 rprojroot              2.0.2      2020-11-15 [1] CRAN (R 4.1.0)
 RSpectra               0.16-0     2019-12-01 [1] CRAN (R 4.1.0)
 rstudioapi             0.13       2020-11-12 [1] CRAN (R 4.1.0)
 rsvd                   1.0.5      2021-04-16 [1] CRAN (R 4.1.0)
 Rtsne                  0.15       2018-11-10 [1] CRAN (R 4.1.0)
 S4Vectors              0.32.3     2021-11-21 [1] Bioconductor
 sass                   0.4.0      2021-05-12 [1] CRAN (R 4.1.0)
 ScaledMatrix           1.2.0      2021-10-26 [1] Bioconductor
 scales                 1.1.1      2020-05-11 [1] CRAN (R 4.1.0)
 scattermore            0.7        2020-11-24 [1] CRAN (R 4.1.0)
 scran                  1.22.1     2021-11-14 [1] Bioconductor
 scrattch.io          * 0.1.0      2022-01-23 [1] Github (AllenInstitute/scrattch.io@9a8c638)
 sctransform            0.3.3      2022-01-13 [1] CRAN (R 4.1.2)
 scuttle                1.4.0      2021-10-26 [1] Bioconductor
 sessioninfo            1.2.2      2021-12-06 [1] CRAN (R 4.1.0)
 Seurat               * 4.1.0      2022-01-14 [1] CRAN (R 4.1.2)
 SeuratData           * 0.2.1      2021-12-08 [1] Github (satijalab/seurat-data@00aa5be)
 SeuratDisk           * 0.0.0.9019 2022-01-23 [1] Github (mojaveazure/seurat-disk@163f1aa)
 SeuratObject         * 4.0.4      2021-11-23 [1] CRAN (R 4.1.0)
 shiny                  1.7.1      2021-10-02 [1] CRAN (R 4.1.0)
 SingleCellExperiment   1.16.0     2021-10-26 [1] Bioconductor
 slam                   0.1-50     2022-01-08 [1] CRAN (R 4.1.2)
 Spaniel              * 1.8.0      2021-10-26 [1] Bioconductor
 sparseMatrixStats      1.6.0      2021-10-26 [1] Bioconductor
 spatstat.core          2.3-2      2021-11-26 [1] CRAN (R 4.1.0)
 spatstat.data          2.1-2      2021-12-17 [1] CRAN (R 4.1.0)
 spatstat.geom          2.3-1      2021-12-10 [1] CRAN (R 4.1.0)
 spatstat.sparse        2.1-0      2021-12-17 [1] CRAN (R 4.1.0)
 spatstat.utils         2.3-0      2021-12-12 [1] CRAN (R 4.1.0)
 SPOTlight            * 0.99.0     2022-01-23 [1] Github (MarcElosua/SPOTlight@ded4136)
 statmod                1.4.36     2021-05-10 [1] CRAN (R 4.1.0)
 stringi                1.7.6      2021-11-29 [1] CRAN (R 4.1.0)
 stringr                1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
 SummarizedExperiment   1.24.0     2021-10-26 [1] Bioconductor
 survival               3.2-13     2021-08-24 [1] CRAN (R 4.1.2)
 tensor                 1.5        2012-05-05 [1] CRAN (R 4.1.0)
 testthat               3.1.2      2022-01-20 [1] CRAN (R 4.1.2)
 tibble                 3.1.6      2021-11-07 [1] CRAN (R 4.1.2)
 tidyr                  1.1.4      2021-09-27 [1] CRAN (R 4.1.0)
 tidyselect             1.1.1      2021-04-30 [1] CRAN (R 4.1.0)
 tm                     0.7-8      2020-11-18 [1] CRAN (R 4.1.0)
 topicmodels          * 0.2-12     2021-01-29 [1] CRAN (R 4.1.0)
 tzdb                   0.2.0      2021-10-27 [1] CRAN (R 4.1.0)
 usethis              * 2.1.5      2021-12-09 [1] CRAN (R 4.1.0)
 utf8                   1.2.2      2021-07-24 [1] CRAN (R 4.1.0)
 uwot                   0.1.11     2021-12-02 [1] CRAN (R 4.1.0)
 vctrs                  0.3.8      2021-04-29 [1] CRAN (R 4.1.0)
 viridisLite            0.4.0      2021-04-13 [1] CRAN (R 4.1.0)
 withr                  2.4.3      2021-11-30 [1] CRAN (R 4.1.0)
 xfun                   0.29       2021-12-14 [1] CRAN (R 4.1.0)
 xml2                   1.3.3      2021-11-30 [1] CRAN (R 4.1.0)
 xtable                 1.8-4      2019-04-21 [1] CRAN (R 4.1.0)
 XVector                0.34.0     2021-10-26 [1] Bioconductor
 yaml                   2.2.1      2020-02-01 [1] CRAN (R 4.1.0)
 zlibbioc               1.40.0     2021-10-26 [1] Bioconductor
 zoo                    1.8-9      2021-03-09 [1] CRAN (R 4.1.0)

 [1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library

Thank you for any help!

**Comment by MarcElosua** [comment]
Issue resolved here - https://github.com/MarcElosua/SPOTlight/issues/39
