### ISSUE TITLE
About PDAC data

### ISSUE THREAD

**Issue by cquzys** [MarcElosua/SPOTlight_deconvolution_analysis#6]
Hello @MarcElosua ,

Thanks for sharing these files. I cannot find the coordinates of each spot in the image of PDAC data. I just saw the relative spatial positions of all spots, but I would like to map these spots to the tissue images. Thus, I need the spot's coordinates in the tissue image. Could you please help me with this? Thanks a lot!

**Comment by MarcElosua** [comment]
Hi @cquzys,

Apologies for the very delayed response. Can you remind me of which files I shared with you? You can download the processed ST and SC data from this [link](https://crgcnag-my.sharepoint.com/:f:/g/personal/melosua_crg_es/EgqkdTRqeDFNkecpKmyQNOEB4WOjVerwccTL28KsPvGnww?e=RMZaXZ). Let me know if this works.

Marc

**Comment by Han117** [comment]
Hi,@MarcElosua,
It's a good study about your method. You could provid the data about processed Mus Musculus Brain ST.rds and SC.rds ?

**Comment by MarcElosua** [comment]
Hi @Han117,

the ST data can be downloaded from 10X genomics public datasets website - https://www.10xgenomics.com/resources/datasets

The single cell data can be downloaded from the Allen brain institute here - https://portal.brain-map.org/atlases-and-data/rnaseq/mouse-whole-cortex-and-hippocampus-10x

Hope this helps!
Marc
